<?= $this->doctype() ?>

<html lang="pl">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Wypożyczalnia samochodów')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/pl.js'))
                ->prependFile($this->basePath('js/flatpickr.js'))
                ->prependFile($this->basePath('js/totop.js'))
                ->prependFile($this->basePath('js/wow.min.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/airbnb.css'))
                ->prependStylesheet($this->basePath('css/flatpickr.min.css'))
                ->prependStylesheet($this->basePath('css/animate.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

        <!-- Font Awesome -->
        <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>
    </head>
    <body id="top">
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>"><span class="fas fa-car fa-2x"></span></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li class="active"><a href="#top"><span class="fab fa-facebook-f"></span></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"><a href="<?= $this->url('home') ?>">Start
                            </a></li>
                        <li><a href="<?= $this->url('flota') ?>">Flota</a></li>
                        <li><a href="<?= $this->url('regulamin') ?>">Regulamin</a></li>
                        <li><a href="<?= $this->url('kontakt') ?>">Kontakt</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </nav>
        <section class="intro">
            <div class="container content">
                <div class="row">
                    <div class="col-md-6">
                        <?= $this->content ?>
                    </div>
                </div>
            </div>
        </section>
        <section class="footer-copyright">
            <div class="container content">
                <div class="row">
                    <div class="col-md-6">
                        &copy; 2018 Wypożyczalnia samochodów Lublin.
                    </div>
                    <div class="col-md-6 text-right">
                        Realizacja Montownia-Stron.
                    </div>
                </div>
            </div>
        </section>
        <?php //echo $this->content ?>

        <script>
            new WOW().init();
        </script>

        <script type="text/javascript">
            $(".nav a").on("click", function () {
                $(".nav").find(".active").removeClass("active");
                $(this).parent().addClass("active");
            });
        </script>
        <script>
            $(function () {
                $('a[href*=#]:not([href=#])').click(function () {
                    if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {

                        var target = $(this.hash);
                        target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                        if (target.length) {
                            $('html,body').animate({
                                scrollTop: target.offset().top
                            }, 1000);
                            return false;
                        }
                    }
                });
            });
        </script>
        <script type="text/javascript">
            $(document).ready(function () {
                //navbar affix
                var s = $(".navbar");
                var pos = s.position();
                $(window).scroll(function () {
                    var windowpos = $(window).scrollTop();
                    if (windowpos >= 300) {
                        s.addClass("stretch");
                    } else {
                        s.removeClass("stretch");
                    }
                });
            });
        </script>
        <script>
            $(document).ready(function () {
                //datepicker
                flatpickr('#data_wypozyczenia', {
                    "locale": "pl",
                    minDate: "today"
                });
                flatpickr('#data_zwrotu', {
                    "locale": "pl",
                    minDate: "today"
                });

                $('#data_wypozyczenia').change(function () {
                    var data_zwrotu_min = $(this).val();
                    flatpickr('#data_zwrotu', {
                        "locale": "pl",
                        minDate: data_zwrotu_min
                    });
                });
            });
        </script>
        <?= $this->inlineScript() ?>
    </body>
</html>
