<?php
//formularz zamówienia
$id = $samochodInfo['id'];
$nazwa = $samochodInfo['nazwa'];
$grupa = $samochodInfo['grupa'];
$cena = $samochodInfo['cena'];
$opis = $samochodInfo['opis'];
$miejsca = $samochodInfo['miejsca'];
$bagaz = $samochodInfo['bagaz'];
$drzwi = $samochodInfo['drzwi'];
$skrzynia = $samochodInfo['skrzynia'];
$paliwo = $samochodInfo['paliwo'];
$klimatyzacja = $samochodInfo['klimatyzacja'];
if ($krok == 'rezerwacja') {
    ?>
    <div class="row">
        <div class="col-md-12">
            <h1>Rezerwacja samochodu</h1>
            <?php
            echo $nazwa
            . '<br />'
            . $opis;
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Zarezerwuj</h2>
            <form class="form-horizontal" action="rezerwuj?id=<?php echo $id; ?>&krok=podsumowanie" method="post">
                <h3>Data rezerwacji</h3>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="data_wypozyczenia">Data wypożyczenia</label>
                        <input type="date" class="form-control" id="data_wypozyczenia" name="data_wypozyczenia" required>
                    </div>
                    <div class="col-md-4">
                        <label for="data_zwrotu">Data zwrotu</label>
                        <input type="date" class="form-control" id="data_zwrotu" placeholder="Nazwisko" name="data_zwrotu" required>
                    </div>
                </div>
                <h3>Dane rezerwującego</h3>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="imie">Imię</label>
                        <input type="text" class="form-control" id="imie" placeholder="Imię" name="imie" required>
                    </div>
                    <div class="col-md-4">
                        <label for="nazwisko">Nazwisko</label>
                        <input type="text" class="form-control" id="nazwisko" placeholder="Nazwisko" name="nazwisko" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="ulica">Telefon kontaktowy</label>
                        <input type="text" class="form-control" id="telefon" placeholder="numer telefonu" name="telefon" required>
                    </div>
                    <div class="col-md-4">
                        <label for="miejscowosc">E-mail</label>
                        <input type="email" class="form-control" id="email" placeholder="E-mail" name="email">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="ulica">Ulica, nr domu/lokalu</label>
                        <input type="text" class="form-control" id="ulica" placeholder="Ulica, nr domu/lokalu" name="ulica" required>
                    </div>
                    <div class="col-md-4">
                        <label for="miejscowosc">Miejscowość</label>
                        <input type="text" class="form-control" id="miejscowosc" placeholder="Miejscowość" name="miejscowosc" required>
                    </div>
                    <div class="col-md-4">
                        <label for="kod_pocztowy">Kod pocztowy</label>
                        <input type="text" class="form-control" id="kod_pocztowy" placeholder="Kod pocztowy" name="kod_pocztowy" pattern="^\d{2}-\d{3}$" title="Format: XX-XXX" required>
                    </div>
                </div>
                <div class="form-group">     
                    <div class="col-sm-12">
                        <input class="form-check-input" type="checkbox" id="defaultCheck1" name="regulamin" required>
                        <label class="form-check-label" for="defaultCheck1">
                            Akceptuję regulamin wynajmu
                        </label>
                    </div>
                    <div class="col-sm-12">
                        <input class="form-check-input" type="checkbox" id="defaultCheck2" name="warunki" required>
                        <label class="form-check-label" for="defaultCheck2">
                            Zapoznałem się z Ogólnymi Warunkami Wynajmu
                        </label>
                    </div>
                </div>
                <div class="form-group">     
                    <div class="col-sm-4">
                        <button type="back" class="btn btn-default">Powrót</button>
                    </div>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-success">Rezerwuj</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <?php
} elseif ($krok == 'podsumowanie') {
    //podsumowanie zamówienia
    $imie = $klient['imie'];
    $nazwisko = $klient['nazwisko'];
    $telefon = $klient['telefon'];
    $email = $klient['email'];
    $ulica = $klient['ulica'];
    $miejscowosc = $klient['miejscowosc'];
    $kod_pocztowy = $klient['kod_pocztowy'];

    $data_wypozyczenia = $klient['data_wypozyczenia'];
    $data_zwrotu = $klient['data_zwrotu'];
    ?>
    <div class="row">
        <div class="col-md-12">
            <h1>Podsumowanie rezerwacji</h1>
            <?php
            echo $nazwa
            . '<br />'
            . $opis;
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1>Twoje dane</h1>
            <ul>
                <li>Imię: <?= $imie ?></li>
                <li>Nazwisko: <?= $nazwisko ?></li>
                <li>Adres: <?= $ulica ?>, <?= $miejscowosc ?></li>
                <li>Kod pocztowy: <?= $kod_pocztowy ?> </li>
                <li>Numer telefonu: <?= $telefon ?> </li>
                <li>E-mail: <?= $email ?> </li>
            </ul>
            <h1>Wypożyczasz samochód w okresie</h1>
            <?php
            echo $data_wypozyczenia . ' - ' . $data_zwrotu;
            ?>
            <p><a href="rezerwuj?id=<?= $id ?>&krok=potwierdzenie" class="btn btn-success">Potwierdzam rezerwację</a></p>
        </div>
    </div>
    <?php
}?>