<?php

foreach ($results as $r) {
    $id = $r->id;
    $nazwa = $r->nazwa;
    $grupa = $r->grupa;
    $cena = $r->cena;
    $opis = $r->opis;
    $miejsca = $r->miejsca;
    $bagaz = $r->bagaz;
    $drzwi = $r->drzwi;
    $skrzynia = $r->skrzynia;
    $paliwo = $r->paliwo;
    $klimatyzacja = $r->klimatyzacja;

    if ($miejsca < 5) {
        $miejsca_string = 'miejsca';
    } else {
        $miejsca_string = 'miejsc';
    }
    if ($klimatyzacja) {
        $klimatyzacja = 'klimatyzacja';
    }

    echo '<div class="row">';
    echo '<div class="col-md-6">{FOTO}' . $id . '</div>';
    echo '<div class="col-md-6">';
    echo '<h2>' . $nazwa . '</h2>';
    echo '<p>' . $opis . '</p>';
    echo '<table class="table borderless">';
    echo '<tr>';
    echo '<td><img src="' . $this->basePath('img/group.png') . '" /> ' . $miejsca . ' ' . $miejsca_string . '</td>';
    echo '<td><img src="' . $this->basePath('img/maintenance.png') . '" /> ' . $bagaz . '</td>';
    echo '<td>' . $drzwi . ' drzwi</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td><img src="' . $this->basePath('img/gearshift.png') . '" /> ' . $skrzynia . '</td>';
    echo '<td><img src="' . $this->basePath('img/dispenser.png') . '" /> ' . $paliwo . '</td>';
    echo '<td><img src="' . $this->basePath('img/air-conditioning.png') . '" /> ' . $klimatyzacja . '</td>';
    echo '</tr>';
    echo '</table>';
    echo '<a href="rezerwacja/rezerwuj?id='.$id.'&krok=rezerwacja" class="btn btn-rezerwuj">REZERWUJ</a>';
    echo '</div>';
    echo '</div>';
}
?>