<div class="search-box">
    <div class="search-body">
        <h3 class="title">Zarezerwuj samochód</h3>
        <form action="flota/szukaj" method="get">
            <div class="form-group">
                <div class="col-md-12">
                    <label for="miejscowosc">Miejsce odbioru</label>
                    <div id="custom-search-input">
                        <div class="input-group col-md-12">
                            <input type="text" name="miejscowosc" class="form-control input-lg" placeholder="Wpisz miejscowość lub nazwę..." />
                            <span class="input-group-btn">
                                <button onclick="getLocation()" class="btn btn-info btn-lg" type="button">
                                    <!--<i class="glyphicon glyphicon glyphicon-screenshot"></i>-->
                                    <i class="fas fa-crosshairs"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6">
                    <label for="data_wypozyczenia">Data odbioru</label>
                    <input class="flatpickr flatpickr-input form-control input-lg" id="data_wypozyczenia"  placeholder="Wybierz datę" name="data_wypozyczenia" readonly="readonly">
                </div>
                <div class="col-md-6">
                    <label for="data_zwrotu">Data zwrotu</label>
                    <input class="flatpickr flatpickr-input form-control input-lg" id="data_zwrotu"  placeholder="Wybierz datę" name="data_zwrotu" readonly="readonly">
                </div>
            </div>
            <div class="form-group"> 
                <div class="col-md-12">
                    <button type="submit" class="btn btn-search">WYSZUKAJ SAMOCHÓD</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        //datepicker
        flatpickr('#data_wypozyczenia', {
            "locale": "pl",
            minDate: "today"
        });
        flatpickr('#data_zwrotu', {
            "locale": "pl",
            minDate: "today"
        });

        $('#data_wypozyczenia').change(function () {
            var data_zwrotu_min = $(this).val();
            flatpickr('#data_zwrotu', {
                "locale": "pl",
                minDate: data_zwrotu_min
            });
        });
    });
</script>